/**
 * @fileoverview Use case for Google OAuth authentication.
 * @module auth/application/usecases/google-auth
 */

import { Inject, Injectable } from '@nestjs/common';
import { User } from '../../domain/entities/user.entity';
import { GoogleService, GoogleUserPayload } from '../../infrastructure/services/google.service';
import { JwtAuthService, TokenPair } from '../../infrastructure/services/jwt.service';
import type { UserRepository } from '../ports/user.repository';
import { USER_REPOSITORY } from '../ports/user.repository';

/**
 * Input DTO for the GoogleAuth use case.
 */
export interface GoogleAuthInput {
  /** Google ID token from mobile client */
  idToken: string;
}

/**
 * Output DTO for the GoogleAuth use case.
 */
export interface GoogleAuthOutput {
  /** Authenticated user data */
  user: {
    id: string;
    email: string;
    name: string;
    avatar?: string;
  };
  /** JWT access token */
  accessToken: string;
  /** JWT refresh token */
  refreshToken: string;
}

/**
 * Use case for authenticating users via Google OAuth.
 * Handles the following flow:
 * 1. Verify Google ID token
 * 2. Find or create user in database
 * 3. Generate JWT tokens for the session
 *
 * @example
 * ```typescript
 * const result = await googleAuthUseCase.execute({
 *   idToken: 'google-id-token-from-client',
 * });
 * // Returns: { user, accessToken, refreshToken }
 * ```
 */
@Injectable()
export class GoogleAuthUseCase {
  /**
   * Creates a new GoogleAuthUseCase instance.
   *
   * @param userRepository - Repository for user persistence
   * @param googleService - Service for Google token verification
   * @param jwtService - Service for JWT token generation
   */
  constructor(
    @Inject(USER_REPOSITORY)
    private readonly userRepository: UserRepository,
    private readonly googleService: GoogleService,
    private readonly jwtService: JwtAuthService,
  ) {}

  /**
   * Executes the Google authentication flow.
   *
   * @param input - Contains the Google ID token
   * @returns Authenticated user and JWT tokens
   * @throws {UnauthorizedException} If Google token verification fails
   */
  async execute(input: GoogleAuthInput): Promise<GoogleAuthOutput> {
    // 1. Verify Google ID token
    const googlePayload: GoogleUserPayload = await this.googleService.verifyIdToken(input.idToken);

    // 2. Find or create user
    const user = await this.findOrCreateUser(googlePayload);

    // 3. Generate JWT tokens
    const tokens: TokenPair = await this.jwtService.generateTokens(user);

    return {
      user: user.toJSON(),
      accessToken: tokens.accessToken,
      refreshToken: tokens.refreshToken,
    };
  }

  /**
   * Finds an existing user by Google ID or creates a new one.
   *
   * @param payload - User data from Google token
   * @returns The existing or newly created user
   * @private
   */
  private async findOrCreateUser(payload: GoogleUserPayload): Promise<User> {
    // Check if user already exists
    const existingUser = await this.userRepository.findByGoogleId(payload.googleId);

    if (existingUser) {
      // Update user info if changed (name, avatar)
      if (existingUser.name !== payload.name || existingUser.avatar !== payload.avatar) {
        const updatedUser = User.create({
          id: existingUser.id,
          email: existingUser.email,
          name: payload.name,
          googleId: existingUser.googleId,
          avatar: payload.avatar,
        });
        return this.userRepository.save(updatedUser);
      }
      return existingUser;
    }

    // Create new user
    const newUser = User.create({
      id: '', // Will be generated by database
      email: payload.email,
      name: payload.name,
      googleId: payload.googleId,
      avatar: payload.avatar,
    });

    return this.userRepository.save(newUser);
  }
}
